### ISSUE TITLE
BLIND SQLI on /setPartner.php on parameter activate

### ISSUE THREAD

**Issue by rondons** [The-XSS-Rat/HD-issues#10]
The application is vulnerable to a Blind SQL Injection (SQLi) attack on page /setPartner.php in the "activate" parameter.

**Steps to reproduce**
- The easiest way to reproduce this vulnerability is through using the following GET method and save it to a file:
![image](https://user-images.githubusercontent.com/73745039/164989351-5e4dc86f-5c5f-4a40-9485-c10601d0b40c.png)

- Then you can retrieve info with sqlmap with risk=2 and level=2 :
![image](https://user-images.githubusercontent.com/73745039/164989205-58747e4f-c608-4d23-8482-6c3fc3404354.png)
![image](https://user-images.githubusercontent.com/73745039/164989461-e83f285e-9e0b-4bdb-946a-c5e691737a5c.png)

**Recommendations**:
- Use Prepared Statements in the application code
Prepared statements allow the association of variables (user input) to data used in SQL queries, making sure that the SQL query itself won’t be changed.
- Data filtering and validation
All data sent by an user should be validated by the application regarding its content.
- Web Application Firewall / WAF:
WAFs work as reverse proxy servers which are responsible for inspecting and validating data that is sent from the website users. This type of solution can protect from attacks as well as trigger alarms when certain pre-configured patterns on the traffic are found.

5th issue so, if you'd like to contact me message me on discord at Sky#3885 :)

**Comment by The-XSS-Rat** [comment]
Thank you <3 fixed by replacing with prepared statements
