### ISSUE TITLE
Vote does not validate the session cookie

### ISSUE THREAD

**Issue by rondons** [The-XSS-Rat/HD-issues#11]
This occurred as a side effect of testing for Blind SQLI. I noticed that whenever you changed the cookie in an automation request, despite it erroring out, it still counted the vote as valid, allowing me to rack up hundreds of votes on my own post.

**Steps to reproduce:**
- You can make a GET request to the endpoint you want to affect such as /index.php?vote=1&postID=169 .
![image](https://user-images.githubusercontent.com/73745039/164990818-553c4e9f-766a-434f-8fd1-0fd9dc734a05.png)
- Change PHPSESSID to another value and watch as the value goes up.
![image](https://user-images.githubusercontent.com/73745039/164990857-d8f91179-47c6-46b0-bb60-f5788b33780c.png)

Alternatively, you can easily reproduce it accidentally like I did. Run sqlmap on "https://hackerats.com/index.php?vote=1&postID=168" with level and risk to 2 to perform the tests on the cookies ;) its a cheaty way but it works!

![image](https://user-images.githubusercontent.com/73745039/164989692-34402254-7da9-4a7c-b30d-08154dda393c.png)

A user can use this to bloat their posts and rise them to the top.

**Recommendations**
- Validate that the cookies are tied to an actual user before accepting it on the voting functionality.

**Comment by The-XSS-Rat** [comment]
Thank you <3 fixed
