### ISSUE TITLE
Reflected XSS on /dm.php on parameter id

### ISSUE THREAD

**Issue by rondons** [The-XSS-Rat/HD-issues#14]
The application is vulnerable to reflected cross-site scripting on the page /dm.php in the "id" parameter.

Given this is a reflected XSS, it can mostly be used to steal other user's cookies through sending them a malicious link.

**Steps to reproduce**
- Go on to "/dm.php?id=121 AND )><script>alert(1)</script>" and that's about it. ;)
![image](https://user-images.githubusercontent.com/73745039/164994308-6b7f9e06-aaf5-4cef-95e2-4a0ffbb40e8c.png)

**Recommendations**: 
To protect most from XSS vulnerabilities, follow three practices:
- Escape user input. Escaping means to convert the key characters in the data that a web page receives to prevent the data from being interpreted in any malicious way. It doesn't allow the special characters to be rendered.
- Validate user input. Treat anything that originates data from outside the system as untrusted. Validate all the input data. Use an allowlist of known, acceptable, good input.
- Sanitize data. Examine and remove unwanted data, such as HTML tags that are deemed to be unsafe. Keep the safe data and remove any unsafe characters from the data.

**Comment by The-XSS-Rat** [comment]
Fixed <3 Thank you for reporting!
