### ISSUE TITLE
SQL Injection on https://hackerats.com/task.php (Severity: CRITICAL)

### ISSUE THREAD

**Issue by CaptainNox** [The-XSS-Rat/HD-issues#19]
Hey Uncle Rat, back once again with a more severe bug now!

The parameter ?id= seems to be vulnerable for SQL Injection.

**Steps to reproduce:**

1) When entering ' or AND 0 in the id parameter, different content reflects.
![image](https://user-images.githubusercontent.com/24610075/180736359-d0518c27-7083-47c8-b974-18241efb5c61.png)
![image](https://user-images.githubusercontent.com/24610075/180736425-9cb38f23-7c79-4a69-b2ff-6f7a45a6b438.png)

2)  Then by using ORDER BY we come down to 5, which still returns true (determined by reflected content on the page)
![image](https://user-images.githubusercontent.com/24610075/180736801-f3efe5aa-c434-4a4e-9e57-3fed62bd8691.png)

3) Using a UNION SELECT, we see that 2 is reflected back on the page, and will provide us with information about the database and server. (To minimize the output reflected, I put a - before the number in the ID parameter)
![image](https://user-images.githubusercontent.com/24610075/180737077-c3faeca0-593d-43ed-ac91-e930318b230a.png)

4) To verify, we put version() in the place of the 2. The version of the operating system gets reflected. BOOOOOM!
![image](https://user-images.githubusercontent.com/24610075/180737984-997da20c-eee8-4494-8c02-ba1fb6fb50b1.png)

I hope you enjoyed my ride throught my manual SQL Injection method. Please use prepared statements next time :D

**Comment by The-XSS-Rat** [comment]
fixed <3 please retest and reopen
