### ISSUE TITLE
Reset Password does not work.

### ISSUE THREAD

**Issue by ivars-vids** [The-XSS-Rat/HD-issues#2]
Reset Password does not work.

**Comment by The-XSS-Rat** [comment]
Thank you for reporting!! 

![image](https://user-images.githubusercontent.com/2901706/163733432-368b956b-3203-4d83-ad21-2c18f9939225.png)

darkshield, it seems the token is not verified properly and set to empty, can you please take a look ? 

Edit: wrong darkshield :p

**Comment by The-XSS-Rat** [comment]
Fixed :) Thank you!
