### ISSUE TITLE
Stored XSS on https://hackerats.com/enterLinks.php (Severity: Medium)

### ISSUE THREAD

**Issue by CaptainNox** [The-XSS-Rat/HD-issues#20]
Back once again, with another bug. The severity of the bug is medium, because the feature to add links is only accessible by admins.

The XSS bug appears in the _link=_ parameter from the POST request made when adding a new link.

**The steps**

1) Send the following request
![mIIg5gfnXh](https://user-images.githubusercontent.com/24610075/181255579-60a978a1-6cbb-40ce-97a1-a1e3e6a72865.png)

2) Watch the alert pop up!
![firefox_cMRng4jWOm](https://user-images.githubusercontent.com/24610075/181255787-04f75c1a-4851-4162-81fb-9be5b088bccd.png)

In order to fix this, use the htmlentities() function in PHP for all user input that will be reflected back to the page!

Kind regards

**Comment by The-XSS-Rat** [comment]
Only admins can do this so put on backlog for now will fix in future

**Comment by Trick-E** [comment]
I have found this to be an issue on a normal user account as well

**Comment by CaptainNox** [comment]
This has been fixed
