### ISSUE TITLE
Reflected XSS on https://hackerats.com/customerQuery.php (Severity: Medium)

### ISSUE THREAD

**Issue by CaptainNox** [The-XSS-Rat/HD-issues#21]
Hey Uncle Rat, the ?id= parameter on https://hackerats.com/customerQuery.php seems to be vulnerable to reflected XSS.

This bug allows an attacker to execute arbitrary javascript inside the browser. 

**Steps to reproduce**

1) Append +><script>alert(document.domain)</script> to https://hackerats.com/customerQuery.php?id=0

2) Press enter and watch the alert pop up!

To fix this bug, please use the htmlentities() function in PHP on all user input.

**Comment by EvaristV2** [comment]
**! IMPORTANT !**

Same vulnerability in https://hackerats.com/customerQuery.php

**Comment by The-XSS-Rat** [comment]
fixed
