### ISSUE TITLE
Stored XSS in https://hackerats.com/adminOverviewReportedDMs.php leads to ATO (Severity: CRITICAL)

### ISSUE THREAD

**Issue by CaptainNox** [The-XSS-Rat/HD-issues#22]
Hey Uncle Rat, this is a big bug you might want to fix :-)

Your page at https://hackerats.com/adminOverviewReportedDMs.php is not escaping the message context properly, causing a users DM to be able to inject javascript into the page (stored). An attacker could report a message on purpose, with malicious javascript in it to leak the session cookies of the admins account, causing full account takeover.

**READ THIS: I WILL NOT IMPLEMENT A REDIRECT NOW, AS IT WOULD DESTROY THE PAGE, BUT DOING THIS IS POSSIBLE CAUSING THE LEAKAGE OF SESSION COOKIES**

**Steps to reproduce**

- First, DM someone (can be yourself) with the XSS vector: "><script>alert(document.domain)</script>
![image](https://user-images.githubusercontent.com/24610075/181265814-4d181d77-5749-4f1c-b228-18873ba13071.png)

- Now, report this DM to the administrators.
![image](https://user-images.githubusercontent.com/24610075/181265295-be31eb77-9803-4118-a591-7225c91847d3.png)

- Wait for an administrator to open the reported DMs page, once the administrator opened the page the javascript will execute. Compromising his account.
![image](https://user-images.githubusercontent.com/24610075/181265443-7c006522-5fa0-4392-a763-dd38274108e4.png)

Fixing this is also possible by using the htmlentities() function in PHP. Use this on all user input.

**Comment by The-XSS-Rat** [comment]
Fixed <4 thanks you
