### ISSUE TITLE
Broken access control on https://hackerats.com/userOverview.php (Severity: High)

### ISSUE THREAD

**Issue by CaptainNox** [The-XSS-Rat/HD-issues#24]
Hey Uncle Rat, I am here with a new bug once again.

https://hackerats.com/userOverview.php doesn't have any authorization implemented, this allows unprivileged users to access this page. This results in leakage of: userID, Username, First name, Last name, Email, Karma, Admin status, Buddy status.

**Patch**
A way to fix this, is implementing the JWT token properly for this page. Have fun patching :D

**Comment by CaptainNox** [comment]
**IMPORTANT**
Also BAC on https://hackerats.com/admin/adminInstructions.php

**Comment by The-XSS-Rat** [comment]
Fixed except for admin instructions since the video is just hidden but public anyway
