### ISSUE TITLE
Non working register code

### ISSUE THREAD

**Issue by YSSVirus** [The-XSS-Rat/HD-issues#3]
The code "Omg | LoveCheese So MuchICouldItEveryDay! <3" is not allowing me to register I tried this multiple ways such as "Omg | LoveCheese So MuchICouldItEveryDay!" "Omg | LoveCheese So MuchICouldItEveryDay! <3"
 Is this no longer a working code?
![63EE5427-3AF7-4E55-A78A-F3D154C9D4CC](https://user-images.githubusercontent.com/56813561/163737515-736721bf-a81b-493e-871e-88b4586fe798.png) or is it suppose to give this error?

**Comment by The-XSS-Rat** [comment]
The code is 

OmgILoveCheeseSoMuchICouldItEveryDay!<3

No spaces and the I is a capital i 🤗

**Comment by YSSVirus** [comment]
> The code is
> 
> OmgILoveCheeseSoMuchICouldItEveryDay!<3
> 
> No spaces and the I is a capital i 🤗

Thank you very much! Can’t believe I looked past that 😂 my bad
